# Generated by Django 5.0.6 on 2024-05-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_profile_image_user_short_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_image",
        ),
        migrations.RemoveField(
            model_name="user",
            name="short_description",
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("doctor", "의사"),
                    ("pharmacist", "약사"),
                    ("general", "일반인"),
                    ("other", "기타"),
                ],
                default="general",
                max_length=10,
            ),
        ),
    ]
