# Generated by Django 5.0.6 on 2024-05-18 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicine", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="용량주의상세정보",
            old_name="일최대투여기준량",
            new_name="일일최대투여기준량",
        ),
        migrations.RenameField(
            model_name="용량주의상세정보",
            old_name="일최대투여량",
            new_name="일일최대투여량",
        ),
    ]
