# Generated by Django 5.0.6 on 2024-05-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="제품",
            name="주성분코드",
            field=models.CharField(max_length=255),
        ),
    ]
