# Generated by Django 5.0.6 on 2024-05-20 03:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicine", "0002_rename_일최대투여기준량_용량주의상세정보_일일최대투여기준량_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="투여기간상세정보",
            old_name="주성분명함량",
            new_name="주성분함량",
        ),
    ]
