# Generated by Django 5.0.6 on 2024-05-21 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicine", "0003_rename_주성분명함량_투여기간상세정보_주성분함량"),
    ]

    operations = [
        migrations.AlterField(
            model_name="제품",
            name="업체코드",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="medicine.업체"
            ),
        ),
    ]
